lib:
  "tmpl.html":
    filePath: "lib/tmpl.html"
  "tmpl.css":
    filePath: lib/tmpl.css
  "tmpl.js":
    filePath: lib/tmpl.js

header:
  links:
    - path: badgers
      name: Badgers
    - path: badgers/more
      name: More Badgers
    - path: githubpage
      name: GitHub Example

content:
  "index":
    title: GitHub Website Runner Example
    filePath: index.html
    tmplHtml: tmpl.html
  "badgers":
    title: Badgers page
    filePath: badgers/index.html
    tmplHtml: tmpl.html
  "badgers/more":
    title: More badgers page
    filePath: badgers/more/index.html
    tmplHtml: tmpl.html
  "githubpage":
    title: GitHub Example
    filePath: README.md
    tmplHtml: tmpl.html
    githubProject: othneildrew/Best-README-Template