lib:
  "tmpl.html":
    filePath: example-website/lib/tmpl.html
    githubProject: ryanlaycock/gitsite
    recacheSeconds: 60
  "index-tmpl.html":
    filePath: example-website/lib/index-tmpl.html
    githubProject: ryanlaycock/gitsite
    recacheSeconds: 60
  "tmpl.css":
    filePath: example-website/lib/tmpl.css
    githubProject: ryanlaycock/gitsite
    recacheSeconds: 60
  "index.css":
    filePath: example-website/lib/index.css
    githubProject: ryanlaycock/gitsite
    recacheSeconds: 60
  "tmpl.js":
    filePath: example-website/lib/tmpl.js
    githubProject: ryanlaycock/gitsite
    recacheSeconds: 600
  "github-markdown-light.css":
    filePath: github-markdown-light.css
    githubProject: sindresorhus/github-markdown-css
    recacheSeconds: 600

header:
  links:
    - path: about
      name: About
    - path: docs
      name: Docs
    - path: showcase
      name: Showcase
  socials:
    - url: https://github.com/ryanlaycock/gitsite
      icon: fa fa-github

siteConfig:
  defaultRecacheSeconds: 1
  title: GitSite

content:
  "":
    title: GitSite
    githubProject: ryanlaycock/gitsite
    filePath: example-website/index/index.html
    tmplHtml: index-tmpl.html
    recacheSeconds: 60
  "about":
    title: About
    githubProject: ryanlaycock/gitsite
    filePath: example-website/about/how-it-works.md
    tmplHtml: tmpl.html
    description: What is GitSite and how is it built?
    date: 2023-10-21
    recacheSeconds: 60
  "docs":
    title: Docs
    githubProject: ryanlaycock/gitsite
    filePath: example-website/docs/docs.md
    tmplHtml: tmpl.html
    date: 2023-10-21
    recacheSeconds: 60
    pinnedPosts:
      - docs/quick-start
      - showcase
      - about
  "docs/quick-start":
    title: Quick Start Guide
    githubProject: ryanlaycock/gitsite
    filePath: example-website/docs/quick-start.md
    tmplHtml: tmpl.html
    date: 2023-10-21
    description: Run this site locally in seconds!
    recacheSeconds: 60
  "showcase":
    title: Showcase
    githubProject: ryanlaycock/gitsite
    filePath: example-website/showcase/showcase.html
    tmplHtml: tmpl.html
    date: 2023-10-21
    description: Peoples awesome sites made with GitSite
    recacheSeconds: 60
