lib:
  "tmpl.html":
    filePath: "lib/tmpl.html"
  "tmpl.css":
    filePath: lib/tmpl.css
  "tmpl.js":
    filePath: lib/tmpl.js

content:
  "index":
    title: GitHub Website Runner Example
    filePath: index.html
  "styles.css":
    title: Default styles file
    filePath: styles.css
  "badgers":
    title: Badgers page
    filePath: badgers/index.html
  "badgers/more":
    title: Badgers page
    filePath: badgers/more/index.html