version: '3'
services:
  gitsite:
    image: ryanlaycock/gitsite:ff814a8
    container_name: gitsite
    restart: unless-stopped
    environment:
      RUST_LOG: debug
      CONFIG_FILE_PATH: example-website/config.yaml
      CONFIG_FILE_GITHUB_PROJECT: ryanlaycock/gitsite
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    networks:
      - app-network
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge